update scripts

diff --git a/bin/AppStore b/bin/AppStore
--- a/bin/AppStore
+++ b/bin/AppStore
@@ -4,41 +4,50 @@ set -o errexit
 set -o pipefail
 set -o nounset
 
-# install MAS
-# see:  https://github.com/mas-cli/mas
-brew install mas
+if [ ! `command -v mas` ] ; then
+  echo "mas required -- run ./homebrew first!" 
+  exit 1
+fi
 
-# 1402042596 AdBlock (1.12.1)
+# 1402042596 AdBlock
 mas install 1402042596 
 
-# 497799835 Xcode (10.1)
+# 497799835 Xcode
 mas install 497799835 
 
-# 425424353 The Unarchiver (4.0.0)
+# 425424353 The Unarchiver
 mas install 425424353 
 
-# 975937182 Fantastical 2 (2.5.6)
+# 975937182 Fantastical 2
 mas install 975937182 
 
-# 465965038 Markdown Pro (1.0.9)
+# 1195426709 Sequence Diagram
+mas install 1195426709
+
+# 465965038 Markdown Pro
 mas install 465965038 
 
-# 775737590 iA Writer (5.1.3)
+# 775737590 iA Writer
 mas install 775737590 
 
-# 1038376059 LogExplorer (0.9.2)
-mas install 1038376059 
-
-# 904280696 Things3 (3.7.3)
-mas install 904280696  
-
-# 803453959 Slack (3.3.3)
-mas install 803453959 
-
-# 918858936 Airmail 3 (3.6.50)
+# 918858936 Airmail 3
 mas install 918858936 
 
-# 1333542190 1Password 7 (7.2.1)
-mas install 1333542190 
+# 904280696 Things3
+mas install 904280696  
 
+# 803453959 Slack
+mas install 803453959 
+
+# 1038376059 LogExplorer
+mas install 1038376059 
+
+# 1142578753 OmniGraffle
+mas install 1142578753
+
+# SnippetsLab
+mas install 1006087419
+
+# 1333542190 1Password 7
+mas install 1333542190 
 
